### PR TITLE
fix for when initially :latest_receipt is nil

### PR DESCRIPTION
**Pull request by hayesmp**
This seems to be the fix for my `'NSInvalidArgumentException', reason: 'data parameter is nil'` problem.

### CODE REVIEW

**Comment by holgersindbaek** [comment]
Nice one. Did you get the gem to work properly in the end?

**Comment by hayesmp** [comment]
Yes. I discovered that the actual receipt data (:latest_receipt) was nil in this case and that's what it was trying to send to be verified.

I had some horrendous problems getting all my gems and cocoapods to work. Everything WAS working until I started trying to integrate StoreKit. I had to tear it all out and start over.

**Comment by hayesmp** [comment]
I'm still editing the gem to see if I can pull out the expiration date to show the user.

**Comment by hayesmp** [comment]
I AM worried that the receipt_data is always nil so I'm going to have to watch that.

**Comment by holgersindbaek** [comment]
@hayesmp Sorry to hear that. Gems and especially Cocoapods do weird stuff in my Rubymotion apps sometimes as well.

Getting the expiration date sounds like a great addition to the info module. I'm quite sure I've already done half the work in the "subscribed?" method. You should check that out.

**Comment by holgersindbaek** [comment]
@hayesmp Remember to push a new PR if you mange to get it to work.

**Comment by hayesmp** [comment]
Yep. New PR. Got it.

It's weird: I'm getting the same data parameter is nil when I tried to pull out the method you created to get the exp date. So it worries me that it's not capturing the receipt. I'll look at this later tonight and make sure I am getting receipt data.

**Comment by holgersindbaek** [comment]
Sounds good. Let me know what you find out.

**Comment by hayesmp** [comment]
As I suspected: the receipt data stays nil. Need to figure out where it's trying to save the reciept...

**Pull request merged**
